# -*- coding: utf-8 -*-
"""Student information collector pro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uo0vWRhgeiwgg5cxEZ6WZcP-U4HOsiwt
"""

# Student Information Collector Pro
student_id="STD-2026-001"

student_name = input("Enter Student Name: ")
father_name = input("Enter Father Name: ")
age = int(input("Enter Age: "))
gender = input("Enter Gender: ")
city = input("Enter City: ")
matric_marks = float(input("Enter Matric Marks: "))
fsc_marks = float(input("Enter FSc Marks: "))

matric_percentage=(matric_marks/1100)*100
fsc_percentage=(fsc_marks/1100)*100
average_percentage=(matric_percentage+fsc_percentage)/2

if average_percentage >= 70:
     scholarship_status= "Eligible for Scholarship"
else:
 scholarship_status="Not Eligible"

print("Student ID :", student_id)
print("Student Name :", student_name)
print("Father's Name :", father_name)
print("Age :", age, "Years")
print("Gender :", gender)
print("City :", city)
print("Matric Marks :", matric_marks, "/ 1100")
print("FSc Marks :", fsc_marks, "/ 1100")
print(f"Matric Percentage : {matric_percentage:.2f}%")
print(f"FSc Percentage : {fsc_percentage:.2f}%")
print(f"Average Percentage : {average_percentage:.2f}%")
print (f"Scholarship Status:{scholarship_status}")

prefix= "STD"
year= "2026"
number= "001"
student_id= f"{prefix}-{year}-{number}"

print (f"Student ID :{student_id}")

#---challenge------

student_name = student_name.upper()

print(f"Student Name : {student_name}")

print(f"length of Student Name :{len(student_name)}")